package com.gsccs.plat.auth.dao;

import com.gsccs.plat.auth.model.SessionT;
import com.gsccs.plat.auth.model.SessionTExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SessionTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int countByExample(SessionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int deleteByExample(SessionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int insert(SessionT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int insertSelective(SessionT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    List<SessionT> selectByExample(SessionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    SessionT selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") SessionT record, @Param("example") SessionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int updateByExample(@Param("record") SessionT record, @Param("example") SessionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int updateByPrimaryKeySelective(SessionT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sessions
     *
     * @mbggenerated Mon Mar 16 17:35:29 CST 2015
     */
    int updateByPrimaryKey(SessionT record);
}