package com.gsccs.plat.auth.dao;

import com.gsccs.plat.auth.model.User;
import com.gsccs.plat.auth.model.UserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserMapper {

	int countByExample(UserExample example);

	int deleteByExample(UserExample example);

	int deleteByPrimaryKey(Long id);

	int insert(User record);

	int insertSelective(User record);

	List<User> selectByExample(UserExample example);
	List<User> selectPageByExample(UserExample example);
	

	
	User selectByPrimaryKey(Long id);

	
	int updateByExampleSelective(@Param("record") User record,
			@Param("example") UserExample example);

	int updateByExample(@Param("record") User record,
			@Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 * 
	 * @mbggenerated Mon Mar 16 15:49:46 CST 2015
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 * 
	 * @mbggenerated Mon Mar 16 15:49:46 CST 2015
	 */
	int updateByPrimaryKey(User record);
}