package com.gsccs.yqfw.work.dao;

import com.gsccs.yqfw.work.model.WorkNotice;
import com.gsccs.yqfw.work.model.WorkNoticeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WorkNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int countByExample(WorkNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int deleteByExample(WorkNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int insert(WorkNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int insertSelective(WorkNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    List<WorkNotice> selectByExample(WorkNoticeExample example);
    
    List<WorkNotice> selectPageByExample(WorkNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    WorkNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") WorkNotice record, @Param("example") WorkNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int updateByExample(@Param("record") WorkNotice record, @Param("example") WorkNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int updateByPrimaryKeySelective(WorkNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqfw_work_notice
     *
     * @mbggenerated Tue Oct 20 11:57:22 CST 2015
     */
    int updateByPrimaryKey(WorkNotice record);
}