package com.gsccs.yqfw.work.dao;

import com.gsccs.yqfw.work.model.WorkPlan;
import com.gsccs.yqfw.work.model.WorkPlanExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WorkPlanMapper {

	int countByExample(WorkPlanExample example);

	int deleteByExample(WorkPlanExample example);

	int deleteByPrimaryKey(String id);

	int insert(WorkPlan record);

	int insertSelective(WorkPlan record);

	List<WorkPlan> selectByExample(WorkPlanExample example);
	List<WorkPlan> selectPageByExample(WorkPlanExample example);

	WorkPlan selectByPrimaryKey(String id);

	int updateByExampleSelective(@Param("record") WorkPlan record,
			@Param("example") WorkPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sqfw_work_plan
	 * 
	 * @mbggenerated Tue Oct 20 11:57:22 CST 2015
	 */
	int updateByExample(@Param("record") WorkPlan record,
			@Param("example") WorkPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sqfw_work_plan
	 * 
	 * @mbggenerated Tue Oct 20 11:57:22 CST 2015
	 */
	int updateByPrimaryKeySelective(WorkPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sqfw_work_plan
	 * 
	 * @mbggenerated Tue Oct 20 11:57:22 CST 2015
	 */
	int updateByPrimaryKey(WorkPlan record);
}