package com.gsccs.yqfw.project.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gsccs.plat.bass.BaseExample;

public class ProjInfoExample extends BaseExample {

	protected String orderByClause;
	protected boolean distinct;
	protected List<Criteria> oredCriteria;

	public ProjInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		
		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		
		public Criteria andStateEqualTo(String value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}
		
		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andPstartdayIsNull() {
			addCriterion("pstartday is null");
			return (Criteria) this;
		}

		public Criteria andPstartdayIsNotNull() {
			addCriterion("pstartday is not null");
			return (Criteria) this;
		}

		public Criteria andPstartdayEqualTo(Date value) {
			addCriterion("pstartday =", value, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayNotEqualTo(Date value) {
			addCriterion("pstartday <>", value, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayGreaterThan(Date value) {
			addCriterion("pstartday >", value, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayGreaterThanOrEqualTo(Date value) {
			addCriterion("pstartday >=", value, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayLessThan(Date value) {
			addCriterion("pstartday <", value, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayLessThanOrEqualTo(Date value) {
			addCriterion("pstartday <=", value, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayIn(List<Date> values) {
			addCriterion("pstartday in", values, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayNotIn(List<Date> values) {
			addCriterion("pstartday not in", values, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayBetween(Date value1, Date value2) {
			addCriterion("pstartday between", value1, value2, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPstartdayNotBetween(Date value1, Date value2) {
			addCriterion("pstartday not between", value1, value2, "pstartday");
			return (Criteria) this;
		}

		public Criteria andPenddayIsNull() {
			addCriterion("pendday is null");
			return (Criteria) this;
		}

		public Criteria andPenddayIsNotNull() {
			addCriterion("pendday is not null");
			return (Criteria) this;
		}

		public Criteria andPenddayEqualTo(Date value) {
			addCriterion("pendday =", value, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayNotEqualTo(Date value) {
			addCriterion("pendday <>", value, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayGreaterThan(Date value) {
			addCriterion("pendday >", value, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayGreaterThanOrEqualTo(Date value) {
			addCriterion("pendday >=", value, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayLessThan(Date value) {
			addCriterion("pendday <", value, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayLessThanOrEqualTo(Date value) {
			addCriterion("pendday <=", value, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayIn(List<Date> values) {
			addCriterion("pendday in", values, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayNotIn(List<Date> values) {
			addCriterion("pendday not in", values, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayBetween(Date value1, Date value2) {
			addCriterion("pendday between", value1, value2, "pendday");
			return (Criteria) this;
		}

		public Criteria andPenddayNotBetween(Date value1, Date value2) {
			addCriterion("pendday not between", value1, value2, "pendday");
			return (Criteria) this;
		}

		public Criteria andEnddayIsNull() {
			addCriterion("endday is null");
			return (Criteria) this;
		}

		public Criteria andEnddayIsNotNull() {
			addCriterion("endday is not null");
			return (Criteria) this;
		}

		public Criteria andEnddayEqualTo(Date value) {
			addCriterion("endday =", value, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayNotEqualTo(Date value) {
			addCriterion("endday <>", value, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayGreaterThan(Date value) {
			addCriterion("endday >", value, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayGreaterThanOrEqualTo(Date value) {
			addCriterion("endday >=", value, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayLessThan(Date value) {
			addCriterion("endday <", value, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayLessThanOrEqualTo(Date value) {
			addCriterion("endday <=", value, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayIn(List<Date> values) {
			addCriterion("endday in", values, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayNotIn(List<Date> values) {
			addCriterion("endday not in", values, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayBetween(Date value1, Date value2) {
			addCriterion("endday between", value1, value2, "endday");
			return (Criteria) this;
		}

		public Criteria andEnddayNotBetween(Date value1, Date value2) {
			addCriterion("endday not between", value1, value2, "endday");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNull() {
			addCriterion("ordernum is null");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNotNull() {
			addCriterion("ordernum is not null");
			return (Criteria) this;
		}

		public Criteria andOrdernumEqualTo(Integer value) {
			addCriterion("ordernum =", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotEqualTo(Integer value) {
			addCriterion("ordernum <>", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThan(Integer value) {
			addCriterion("ordernum >", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThanOrEqualTo(Integer value) {
			addCriterion("ordernum >=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThan(Integer value) {
			addCriterion("ordernum <", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThanOrEqualTo(Integer value) {
			addCriterion("ordernum <=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumIn(List<Integer> values) {
			addCriterion("ordernum in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotIn(List<Integer> values) {
			addCriterion("ordernum not in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumBetween(Integer value1, Integer value2) {
			addCriterion("ordernum between", value1, value2, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotBetween(Integer value1, Integer value2) {
			addCriterion("ordernum not between", value1, value2, "ordernum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table yqfw_project
	 * 
	 * @mbggenerated do_not_delete_during_merge Mon Nov 02 11:55:52 CST 2015
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table yqfw_project
	 * 
	 * @mbggenerated Mon Nov 02 11:55:52 CST 2015
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}