package com.gsccs.yqfw.corp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.yqfw.corp.model.MonitorType;
import com.gsccs.yqfw.corp.model.MonitorTypeExample;

public interface MonitorTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int countByExample(MonitorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int deleteByExample(MonitorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int insert(MonitorType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int insertSelective(MonitorType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    List<MonitorType> selectByExample(MonitorTypeExample example);
    List<MonitorType> selectPageByExample(MonitorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    MonitorType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int updateByExampleSelective(@Param("record") MonitorType record, @Param("example") MonitorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int updateByExample(@Param("record") MonitorType record, @Param("example") MonitorTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int updateByPrimaryKeySelective(MonitorType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_monit_type
     *
     * @mbggenerated Wed Oct 21 11:39:56 CST 2015
     */
    int updateByPrimaryKey(MonitorType record);
}