package com.gsccs.yqfw.gis.dao;

import com.gsccs.yqfw.gis.model.GisConf;
import com.gsccs.yqfw.gis.model.GisConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GisConfMapper {
   
    int countByExample(GisConfExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_gis_conf
     *
     * @mbggenerated Mon Dec 21 14:24:12 CST 2015
     */
    int deleteByPrimaryKey(String authkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_gis_conf
     *
     * @mbggenerated Mon Dec 21 14:24:12 CST 2015
     */
    int insert(GisConf record);

  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_gis_conf
     *
     * @mbggenerated Mon Dec 21 14:24:12 CST 2015
     */
    List<GisConf> selectByExample(GisConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_gis_conf
     *
     * @mbggenerated Mon Dec 21 14:24:12 CST 2015
     */
    GisConf selectByPrimaryKey(String authkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_gis_conf
     *
     * @mbggenerated Mon Dec 21 14:24:12 CST 2015
     */
    int updateByExample(@Param("record") GisConf record, @Param("example") GisConfExample example);

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqfw_gis_conf
     *
     * @mbggenerated Mon Dec 21 14:24:12 CST 2015
     */
    int updateByPrimaryKey(GisConf record);
}