package com.gsccs.yqfw.gis.dao;

import com.gsccs.yqfw.gis.model.LandPoint;
import com.gsccs.yqfw.gis.model.LandPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LandPointMapper {

	int countByExample(LandPointExample example);

	int deleteByExample(LandPointExample example);

	int deleteByPrimaryKey(String id);

	int insert(LandPoint record);

	int insertSelective(LandPoint record);

	
	List<LandPoint> selectByExample(LandPointExample example);
	List<LandPoint> selectPageByExample(LandPointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_point
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	LandPoint selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_point
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByExampleSelective(@Param("record") LandPoint record,
			@Param("example") LandPointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_point
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByExample(@Param("record") LandPoint record,
			@Param("example") LandPointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_point
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByPrimaryKeySelective(LandPoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_point
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByPrimaryKey(LandPoint record);
}