package com.gsccs.yqfw.gis.dao;

import com.gsccs.yqfw.gis.model.LandInfo;
import com.gsccs.yqfw.gis.model.LandInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LandInfoMapper {

	int countByExample(LandInfoExample example);

	int deleteByExample(LandInfoExample example);

	int deleteByPrimaryKey(String id);

	int insert(LandInfo record);

	int insertSelective(LandInfo record);

	List<LandInfo> selectByExample(LandInfoExample example);
	List<LandInfo> selectPageByExample(LandInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_info
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	LandInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_info
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByExampleSelective(@Param("record") LandInfo record,
			@Param("example") LandInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_info
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByExample(@Param("record") LandInfo record,
			@Param("example") LandInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_info
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByPrimaryKeySelective(LandInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_land_info
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByPrimaryKey(LandInfo record);
}