package com.gsccs.yqfw.gis.dao;

import com.gsccs.yqfw.gis.model.MarkerFactor;
import com.gsccs.yqfw.gis.model.MarkerFactorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarkerFactorMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_marker_factor
	 * 
	 * @mbggenerated Fri Oct 23 10:04:55 CST 2015
	 */
	int countByExample(MarkerFactorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_marker_factor
	 * 
	 * @mbggenerated Fri Oct 23 10:04:55 CST 2015
	 */
	int deleteByExample(MarkerFactorExample example);

	int deleteByPrimaryKey(String id);

	int insert(MarkerFactor record);

	List<MarkerFactor> selectByExample(MarkerFactorExample example);

	List<MarkerFactor> selectPageByExample(MarkerFactorExample example);

	MarkerFactor selectByPrimaryKey(String id);

	int updateByExample(@Param("record") MarkerFactor record,
			@Param("example") MarkerFactorExample example);

	int updateByPrimaryKey(MarkerFactor record);
}