package com.gsccs.yqfw.gis.dao;

import com.gsccs.yqfw.gis.model.PipeLine;
import com.gsccs.yqfw.gis.model.PipeLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PipeLineMapper {
	int countByExample(PipeLineExample example);

	int deleteByExample(PipeLineExample example);

	int deleteByPrimaryKey(String id);

	int insert(PipeLine record);

	int insertSelective(PipeLine record);

	
	List<PipeLine> selectByExample(PipeLineExample example);
	List<PipeLine> selectPageByExample(PipeLineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_pipe_net
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	PipeLine selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_pipe_net
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByExampleSelective(@Param("record") PipeLine record,
			@Param("example") PipeLineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_pipe_net
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByExample(@Param("record") PipeLine record,
			@Param("example") PipeLineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_pipe_net
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByPrimaryKeySelective(PipeLine record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table yqfw_pipe_net
	 * 
	 * @mbggenerated Wed Oct 21 11:39:56 CST 2015
	 */
	int updateByPrimaryKey(PipeLine record);
}